// Native Chromium geometry on actual minified-bundle renderings; synthetic data only.
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {existsSync,mkdtempSync,readFileSync,writeFileSync,rmSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {dirname,join,relative,isAbsolute,basename} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const project=dirname(dirname(fileURLToPath(import.meta.url)));
const browser=[process.env.LUBI_BROWSER,'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe','/usr/bin/chromium','/usr/bin/google-chrome'].find(p=>p&&existsSync(p));
if(!browser) { if(process.env.LUBI_REQUIRE_BROWSER==='1')throw new Error('Native browser required for planning layout'); console.log('SKIP planning layout: browser unavailable'); }
else {
 const preview=spawnSync(process.execPath,['test/preview.mjs'],{cwd:project,encoding:'utf8',timeout:60000,maxBuffer:4*1024*1024});assert.equal(preview.status,0,preview.stderr+preview.stdout);
 const tmp=mkdtempSync(join(tmpdir(),'lubi-planning-layout-'));
 try {
  for(const theme of ['light','dark'])for(const width of [1400,1000,901,900,850,800,390,320]) {
   const cases=[];
   for(const mode of ['calendar','gantt','list'])for(const period of ['day','week','month']) {
    const name=`planning-${mode}-${period}`;const html=readFileSync(join(project,'preview',theme==='dark'?'dark':'',name+'.html'),'utf8');
    // Off-screen srcdoc frames may not receive rAF; geometry reads flush layout after fonts are ready.
    const probe=`<script>addEventListener('load',()=>{(document.fonts?.ready||Promise.resolve()).then(()=>setTimeout(()=>{
      const rect=e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height}};
      const head=document.querySelector('.lubi-planning-head'),main=document.querySelector('.lubi-planning-main, .lubi-today-main'),root=document.querySelector('.lubi-root');
      const switches=[...head.querySelectorAll('.lubi-seg')].map(e=>({box:rect(e),display:getComputedStyle(e).display,selected:e.querySelectorAll('[aria-pressed="true"]').length}));
      const out={name:${JSON.stringify(name)},width:innerWidth,overflow:document.documentElement.scrollWidth-innerWidth,rootOverflow:root.scrollWidth-root.clientWidth,pageOverflow:document.querySelector(".lubi-page").scrollWidth-document.querySelector(".lubi-page").clientWidth,switches,head:rect(head),main:rect(main),debug:[...document.querySelectorAll("body *")].filter(e=>rect(e).right>innerWidth+1&&rect(e).width>0).slice(0,12).map(e=>({cls:e.className,rect:rect(e),pos:getComputedStyle(e).position,overflow:getComputedStyle(e).overflowX})),rootBox:rect(root),titleLeft:[...document.querySelectorAll('.lubi-task-title,.lubi-gantt-title,.lubi-month-task')].every(e=>getComputedStyle(e).textAlign==='left'),week:null,month:null,list:null};
      out.startButtons=[...root.querySelectorAll('.lubi-task-start')].map(button=>{
        const row=button.closest('.lubi-task'),text=row.querySelector('.lubi-task-title-text'),b=rect(button),t=rect(text),r=rect(row),svg=rect(button.querySelector('svg'));
        const aligned=Math.abs((svg.top+svg.height/2)-(t.top+parseFloat(getComputedStyle(text).lineHeight)/2))<=.5;
        const inside=b.left>=r.left-.5&&b.right<=r.right+.5&&b.top>=r.top-.5&&b.bottom<=r.bottom+.5;
        button.focus({preventScroll:true});const focused=rect(button);button.blur();
        return {aligned,inside,focusInside:focused.left>=r.left-.5&&focused.right<=r.right+.5,button:b,title:t,row:r};
      });
      const side=document.querySelector('.lubi-task-lists');
      out.sidebar=rect(side);
      const importer=root.querySelector(".lubi-topbar-import"),aiButton=root.querySelector(".lubi-topbar-ai");out.jsonImport={visible:getComputedStyle(importer).display!=="none"&&rect(importer).width>0,left:importer.nextElementSibling===aiButton&&rect(importer).right<=rect(aiButton).left+.5,inside:rect(importer).left>=0&&rect(importer).right<=innerWidth,secondary:!importer.classList.contains("mod-cta")};
      const ai=root.querySelector(".lubi-topbar-ai"),cta=root.querySelector(".lubi-topbar-cta");out.ai={visible:getComputedStyle(ai).display!=="none"&&rect(ai).width>0,left:ai.nextElementSibling===cta&&rect(ai).right<=rect(cta).left+.5,inside:rect(ai).left>=0&&rect(ai).right<=innerWidth,secondary:!ai.classList.contains("mod-cta"),named:(ai.getAttribute("aria-label")||document.getElementById(ai.getAttribute("aria-labelledby"))?.textContent)==="AI 创建任务"};
      const stats=head.querySelector('.lubi-today-summary'),range=head.querySelector('.lubi-schedule-range'),nav=head.querySelector('.lubi-nav');
      out.headerSummary=stats?{parent:stats.parentElement===head,afterDate:stats.previousElementSibling===range,beforeNav:stats.nextElementSibling===nav,box:rect(stats),date:rect(range),nav:rect(nav),items:[...stats.children].map(rect),inside:rect(stats).left>=rect(head).left&&rect(stats).right<=rect(head).right,duplicate:document.querySelectorAll('.lubi-today-summary').length}:null;

      out.tabs=[...root.querySelectorAll(".lubi-topbar-tabs button > span:not(.lubi-icon)")].map(e=>({text:e.textContent,visible:getComputedStyle(e).display!=="none"&&rect(e).width>0&&rect(e).height>0}));
      out.summary={distribution:side.querySelectorAll('.lubi-distribution').length,plans:side.querySelectorAll('.lubi-plan-card').length};
      const ring=side.querySelector('.lubi-donut');if(ring){const card=side.querySelector('.lubi-distribution'),legend=side.querySelector('.lubi-legend'),plan=side.querySelector('.lubi-plan-card'),inbox=side.querySelector('.lubi-list-card');
        out.summary={...out.summary,ring:rect(ring),legend:rect(legend),card:rect(card),plan:rect(plan),inbox:rect(inbox),open:side.querySelector('details').open,progress:rect(side.querySelector('.lubi-plan-progress')),inside:[ring,legend,plan,inbox].every(e=>rect(e).left>=rect(side).left-.5&&rect(e).right<=rect(side).right+.5)};}
      const timeline=document.querySelector('.lubi-timeline');if(timeline){const sc=timeline.parentElement;sc.scrollTop=0;const zero=timeline.querySelector('.lubi-hour-label'),last=timeline.querySelector('.lubi-hour-label.is-day-end'),sr=rect(sc);const zeroVisible=rect(zero).top>=sr.top&&rect(zero).bottom<=sr.bottom;sc.scrollTop=sc.scrollHeight;out.timeline={zero:zero.textContent,end:last.textContent,zeroVisible,endVisible:rect(last).top>=rect(sc).top&&rect(last).bottom<=rect(sc).bottom,cursor:getComputedStyle(timeline.querySelector('.lubi-tl-canvas')).cursor,plans:timeline.querySelectorAll('.lubi-plan').length,summary:document.querySelectorAll('.lubi-today-summary').length};}
      const week=document.querySelector('.lubi-week-body');if(week){
        const headers=[...document.querySelectorAll('.lubi-week-day')],cols=[...week.querySelectorAll('.lubi-week-col')];
        const first=week.querySelector('.lubi-week-hour'),end=week.querySelector('.lubi-week-hour.is-day-end');week.scrollTop=0;
        const fr=rect(first),wr=rect(week);const zeroVisible=fr.top>=wr.top-.5&&fr.bottom<=wr.bottom+.5;
        week.scrollTop=week.scrollHeight;const er=rect(end),axis=rect(week);
        out.week={scroll:getComputedStyle(week.parentElement.parentElement).overflowX,cardWidth:week.parentElement.parentElement.clientWidth,cardScroll:week.parentElement.parentElement.scrollWidth,marks:[...document.querySelectorAll(".lubi-wblock.is-done .lubi-wblock-title")].every(e=>["none","normal"].includes(getComputedStyle(e,"::before").content)&&getComputedStyle(e).textDecorationLine.includes("line-through")),allDayDone:[...document.querySelectorAll(".lubi-allday-chip.is-done")].every(e=>getComputedStyle(e).textDecorationLine.includes("line-through")),count:cols.length,align:headers.every((h,i)=>Math.abs(rect(h).left-rect(cols[i]).left)<=1&&Math.abs(rect(h).width-rect(cols[i]).width)<=1),zero:first.textContent,zeroVisible,end:end.textContent,endVisible:er.top>=axis.top-.5&&er.bottom<=axis.bottom+.5,cursor:cols.every(c=>getComputedStyle(c).cursor==='crosshair')};
      }
      const month=document.querySelector('.lubi-month-calendar');if(month){const sc=month.parentElement;out.month={cells:month.querySelectorAll('.lubi-month-day').length,inside:rect(sc).right<=innerWidth+1,scroll:getComputedStyle(sc).overflowX,minCell:Math.min(...[...month.querySelectorAll('.lubi-month-day')].map(c=>rect(c).width))};}
      const list=document.querySelector('.lubi-plan-range-list');if(list)out.list={inside:rect(list).right<=innerWidth+1,sidebarCards:document.querySelectorAll('.lubi-task-lists .lubi-list-card').length,rows:list.querySelectorAll('.lubi-task').length,selected:!!side.querySelector('.lubi-selected-day-list'),selectedFirst:side.firstElementChild===side.querySelector('.lubi-selected-day-list'),quick:!!side.querySelector('.lubi-selected-day-list .lubi-quick-add input'),inboxBelow:side.querySelector('.lubi-selected-day-list')?.nextElementSibling?.querySelector('h3')?.textContent==='未安排'};
      out.projectHeadings=[...document.querySelectorAll('.lubi-gantt-project-heading')].map(e=>({name:rect(e.querySelector('.lubi-gantt-name')),taskName:rect(e.nextElementSibling.querySelector('.lubi-gantt-name')),inside:rect(e.querySelector('.lubi-gantt-name')).left>=rect(e).left-.5,plain:!e.querySelector('button,input,.lubi-gantt-bar,.lubi-gantt-handle')&&!e.hasAttribute('data-task-id'),text:e.textContent,ids:e.dataset.projectId}));
      if(document.querySelector('.lubi-gantt-table')){
        LubiGanttLabels.fitGanttLabels(document);
        out.ganttDetails={grids:[...document.querySelectorAll('.lubi-gantt-project-group')].map(group=>{const label=group.querySelector('.lubi-gantt-project-heading'),tasks=[...group.querySelectorAll('.lubi-gantt-row')],reference=[...tasks[0].querySelectorAll('.lubi-gantt-grid > div')];return {count:reference.length,expected:document.querySelector('.lubi-daily-gantt-scroll')?24:Number(document.querySelector('.lubi-gantt-table').dataset.ganttCount),aligned:tasks.every(task=>[...task.querySelectorAll('.lubi-gantt-grid > div')].every((c,i)=>Math.abs(rect(c).left-rect(reference[i]).left)<=1&&Math.abs(rect(c).width-rect(reference[i]).width)<=1))&&Math.abs(rect(label).top-rect(tasks[0]).top)<=1&&Math.abs(rect(label).bottom-rect(tasks.at(-1)).bottom)<=1,indented:rect(label).right<=rect(tasks[0].querySelector('.lubi-gantt-name')).left+1}}),labels:[...document.querySelectorAll('.lubi-gantt-bar')].map(bar=>{const label=bar.querySelector('.lubi-gantt-bar-label');return {shown:getComputedStyle(label).visibility!=='hidden',fits:label.scrollWidth<=bar.clientWidth-16}})};
        out.ganttVisual={centered:[...document.querySelectorAll('.lubi-gantt-project-heading > .lubi-gantt-name')].every(e=>getComputedStyle(e).textAlign==='center'),futureWhite:[...document.querySelectorAll('.lubi-gantt-grid > .is-weekend.is-future')].every(e=>['rgba(0, 0, 0, 0)',getComputedStyle(document.querySelector('.lubi-gantt-track')).backgroundColor].includes(getComputedStyle(e).backgroundColor)),textFits:[...document.querySelectorAll('.lubi-gantt-title')].every(e=>{const t=e.querySelector('span:not(.lubi-sr-only)'),r=rect(e),v=rect(t);return v.top>=r.top-.5&&v.bottom<=r.bottom+.5}),corner:true};
        out.ganttVisual.centered=[...document.querySelectorAll('.lubi-gantt-project-heading')].every(group=>{const label=group.querySelector('.lubi-gantt-name'),g=rect(group),r=rect(label);return Math.abs((g.top+g.bottom)-(r.top+r.bottom))<=2&&Math.abs((g.left+g.right)-(r.left+r.right))<=2&&getComputedStyle(label).textAlign==='center'});
        out.ganttVisual.noLeftAccent=[...document.querySelectorAll('.lubi-gantt-bar')].every(bar=>getComputedStyle(bar).boxShadow==='none');
        const completed=[...document.querySelectorAll('.lubi-gantt-bar.is-done')];out.ganttVisual.completed=completed.length>0&&completed.every(bar=>{const style=getComputedStyle(bar),row=bar.closest('.lubi-gantt-row'),filled=style.backgroundColor;bar.classList.remove('is-done');const empty=getComputedStyle(bar).backgroundColor;bar.classList.add('is-done');return filled!==empty&&style.getPropertyValue('--chip').trim()===getComputedStyle(row).getPropertyValue('--chip').trim()&&!getComputedStyle(row.querySelector('.lubi-gantt-title')).textDecorationLine.includes('line-through')});
        out.ganttVisual.resize=[...document.querySelectorAll('.lubi-gantt-bar > .lubi-gantt-handle.is-start')].filter(h=>{const b=rect(h.closest('.lubi-gantt-bar')),scroll=h.closest('.lubi-gantt-scroll'),sc=rect(scroll);return b.width>24&&b.left>=sc.left&&b.left+2<Math.min(sc.left+scroll.clientLeft+scroll.clientWidth,innerWidth)&&b.top>=sc.top&&b.bottom<Math.min(sc.top+scroll.clientTop+scroll.clientHeight,innerHeight)}).every(h=>{const bar=h.closest('.lubi-gantt-bar'),b=rect(bar),hit=document.elementFromPoint(b.left+1,b.top+b.height/2);return hit&&h.contains(hit)&&getComputedStyle(hit).cursor==='ew-resize'});
        const sc=document.querySelector('.lubi-gantt-scroll'),corner=sc.querySelector('.lubi-gantt-heading > .lubi-gantt-name');const oldLeft=sc.scrollLeft,oldTop=sc.scrollTop;sc.scrollLeft=120;sc.scrollTop=60;
        const c=rect(corner),s=rect(sc);out.ganttVisual.corner=c.left>=s.left-.5&&c.top>=s.top-.5&&corner.scrollWidth<=corner.clientWidth+1;sc.scrollLeft=oldLeft;sc.scrollTop=oldTop;
        {
          const table=document.querySelector('.lubi-gantt-table'),d=table.dataset.ganttFrom.split('-').map(Number),fixed=new Date(d[0],d[1]-1,d[2],6,0,0);LubiGanttLabels.updateGanttNow(table,fixed);
          const marks=[...table.querySelectorAll('.lubi-gantt-today')];out.ganttVisual.marks=marks.length===table.querySelectorAll('.lubi-gantt-row').length&&marks.every(m=>Number(getComputedStyle(m).zIndex)>Number(getComputedStyle(table.querySelector('.lubi-gantt-bar')).zIndex)&&!m.hidden&&Math.abs(parseFloat(m.style.left)-.25/Number(table.dataset.ganttCount)*100)<.0001);
          LubiGanttLabels.updateGanttNow(document,new Date(d[0],d[1]-1,d[2],18,0,0));out.ganttVisual.moves=marks.every(m=>Math.abs(parseFloat(m.style.left)-.75/Number(table.dataset.ganttCount)*100)<.0001);
          LubiGanttLabels.updateGanttNow(document,new Date(d[0]-1,0,1));out.ganttVisual.outside=marks.every(m=>m.hidden);LubiGanttLabels.updateGanttNow(document);
        }
        const bar=document.querySelector('.lubi-gantt-bar'),label=bar?.querySelector('.lubi-gantt-bar-label');
        if(bar&&label){const width=bar.style.width,text=label.textContent;label.textContent='10/1–10/31';bar.style.width='20px';LubiGanttLabels.fitGanttLabel(bar);const narrow=getComputedStyle(label).visibility==='hidden';bar.style.width='240px';LubiGanttLabels.fitGanttLabel(bar);const wide=getComputedStyle(label).visibility==='visible';bar.style.width='20px';LubiGanttLabels.fitGanttLabels(document);out.labelResize={narrow,wide,narrowAgain:getComputedStyle(label).visibility==='hidden'};bar.style.width=width;label.textContent=text;LubiGanttLabels.fitGanttLabel(bar);}
      }
      parent.postMessage({type:'planning-layout',value:out},'*');
    },0));},{once:true});<\/script>`;
    cases.push({name,html:html.replace('</body>',probe+'</body>')});
   }
   const parent=`<!doctype html><html><body style="margin:0"><pre id="results"></pre><script>
     const cases=${JSON.stringify(cases).replaceAll('<','\\u003c')};const results=[];
     addEventListener('message',e=>{if(e.data?.type==='planning-layout'){results.push(e.data.value);if(results.length===cases.length)document.getElementById('results').textContent='LUBI_PLANNING:'+encodeURIComponent(JSON.stringify(results));}});
     for(const c of cases){const frame=document.createElement('iframe');frame.style.cssText='border:0;display:block;width:${width}px;height:850px';frame.srcdoc=c.html;document.body.append(frame);}
     </script></body></html>`;
   const file=join(tmp,`${theme}-${width}.html`);writeFileSync(file,parent,'utf8');
   const run=spawnSync(browser,['--headless=new','--disable-gpu','--disable-extensions','--no-first-run','--no-default-browser-check','--disable-background-networking','--window-size=1920,1000','--force-device-scale-factor=1','--virtual-time-budget=4000',`--user-data-dir=${join(tmp,`profile-${theme}-${width}`)}`,'--dump-dom',pathToFileURL(file).href],{encoding:'utf8',timeout:45000,maxBuffer:20*1024*1024});
   assert.equal(run.status,0,run.error||run.stderr?.slice(-700));const found=[...run.stdout.matchAll(/LUBI_PLANNING:(%5B[^<\s]+)/g)].at(-1);assert(found,`missing planning metrics: ${run.stderr?.slice(-500)} ${run.stdout.slice(-500)}`);
   const metrics=JSON.parse(decodeURIComponent(found[1]));assert.equal(metrics.length,9);
   for(const g of metrics){const label=`${theme} ${width}px ${g.name}`;
     assert(g.jsonImport.visible&&g.jsonImport.left&&g.jsonImport.inside&&g.jsonImport.secondary,label+' JSON import left of AI');assert(g.ai.visible&&g.ai.left&&g.ai.inside&&g.ai.secondary&&g.ai.named,label+' direct AI button left of primary creation');assert.equal(g.width,width,label+' native viewport width');assert.deepEqual(g.tabs.map(tab=>tab.text),['计划','回顾'],label+' two top-level pages');assert(g.tabs.every(tab=>tab.visible),label+' no blank narrow navigation');assert(g.overflow<=1,label+' page overflow '+JSON.stringify(g));
     assert.equal(g.switches.length,2,label+' exactly two view/range groups');assert(g.switches.every(s=>s.display!=='none'&&s.box.width>0&&s.box.left>=0&&s.box.right<=width+1&&s.selected===1),label+' controls visible '+JSON.stringify(g));
     const wide=g.rootBox.width>900;
     if(wide)assert(Math.abs(g.sidebar.width-300)<=.5,label+' sidebar matches calendar-day 300px');
     else assert(Math.abs(g.sidebar.width-g.main.width)<=.5,label+' narrow sidebar fills the available main width');
     assert(g.main.width>0&&g.main.right<=width+1,label+' main stays visible');assert(g.titleLeft,label+' task titles left aligned');
     assert(g.startButtons.length>0,label+' rendered start triangles');
     assert(g.startButtons.every(b=>b.aligned&&b.inside&&b.focusInside),label+' start triangles align to first title line and stay inside rows, including focus '+JSON.stringify(g.startButtons));
     if(g.name==='planning-calendar-day'){if(wide){assert(g.main.right<=g.sidebar.left&&Math.abs(g.main.top-g.sidebar.top)<=1,label+' timeline left, summary right and top-aligned '+JSON.stringify(g.sidebar));}else assert(g.main.bottom<=g.sidebar.top,label+' narrow summary below timeline, without overlap');const s=g.summary;assert(s.distribution===1&&s.plans===1&&s.open&&s.inside,label+' shared day cards '+JSON.stringify(s));assert(s.ring.width>=110&&Math.abs(s.ring.width-s.ring.height)<1&&s.legend.width>=80,label+' readable ring/legend '+JSON.stringify(s));assert(s.card.bottom<=s.plan.top&&s.plan.bottom<=s.inbox.top&&s.progress.width>0,label+' separate cards and progress '+JSON.stringify(s));}
     else {assert.equal(g.headerSummary,null,label+' no added summaries in other presentations');assert(g.summary.distribution===0&&g.summary.plans===0,label+' other sidebars unchanged');if(wide)assert(g.main.right<=g.sidebar.left&&Math.abs(g.main.top-g.sidebar.top)<=1,label+' main left, existing sidebar right and top-aligned');else assert(g.main.bottom<=g.sidebar.top,label+' narrow sidebar below main without overlap');}
     if(g.name==='planning-calendar-day'){const h=g.headerSummary;assert(h&&h.parent&&h.afterDate&&h.beforeNav&&h.inside&&h.duplicate===1,label+' summary follows date in header');if(g.rootBox.width>=1200)assert(h.box.left>=h.date.right&&h.box.right<=h.nav.left&&Math.abs(h.box.top+h.box.height/2-h.date.top-h.date.height/2)<=1&&h.items.every(item=>Math.abs(item.top+item.height/2-h.date.top-h.date.height/2)<=1),label+' wide summary shares the date row without overlap');const t=g.timeline;assert(t&&t.zero==='00:00'&&t.end==='24:00'&&t.zeroVisible&&t.endVisible&&t.cursor==='crosshair'&&t.plans>0&&t.summary===1,label+' full daily timeline '+JSON.stringify(t));}
     if(g.week){assert((g.week.cardScroll<=g.week.cardWidth+1||g.week.scroll==='auto')&&g.pageOverflow<=1,label+' calendar scroll containment '+JSON.stringify(g));assert.equal(g.week.count,g.name.endsWith('-day')?1:7,label+' calendar columns');assert(g.week.marks&&g.week.allDayDone&&g.week.align&&g.week.zero==='00:00'&&g.week.end==='24:00'&&g.week.zeroVisible&&g.week.endVisible&&g.week.cursor,label+' aligned full-day axis '+JSON.stringify(g.week));}
     if(g.month){assert([28,35,42].includes(g.month.cells)&&g.month.inside&&g.month.scroll==='auto'&&g.month.minCell>=80,label+' month scroll/geometry '+JSON.stringify(g.month));}
     if(g.name.startsWith('planning-gantt-')){assert(g.ganttVisual.noLeftAccent&&g.ganttVisual.resize&&g.ganttVisual.completed&&g.ganttVisual.centered&&g.ganttVisual.futureWhite&&g.ganttVisual.textFits&&g.ganttVisual.corner,label+' centered projects, future weekends white and unclipped text/corner '+JSON.stringify(g.ganttVisual));assert(g.ganttVisual.marks&&g.ganttVisual.moves&&g.ganttVisual.outside,label+' continuous fractional current-time marker '+JSON.stringify(g.ganttVisual));assert(g.ganttDetails.grids.every(p=>p.count===p.expected&&p.count>0&&p.aligned&&p.indented),label+' continuous grid and task indent');assert(g.ganttDetails.labels.every(p=>!p.shown||p.fits),label+' no clipped or partial label');assert(g.labelResize?.narrow&&g.labelResize.wide&&g.labelResize.narrowAgain,label+' label hides/shows after resizing');assert(g.projectHeadings.length>0,label+' project headings exist');assert(g.projectHeadings.every(h=>h.plain&&h.inside&&h.name.right<=h.taskName.left+1),label+' project headings align with sticky task column without actions '+JSON.stringify(g.projectHeadings));assert(new Set(g.projectHeadings.map(h=>h.ids)).size===g.projectHeadings.length,label+' no repeated project heading');}
     if(g.list){assert(g.list.inside&&g.list.sidebarCards===2&&g.list.rows>0&&g.list.selected&&g.list.selectedFirst&&g.list.quick&&g.list.inboxBelow,label+' main list retained with selected-day card above inbox');}
   }
   console.log(`PASS planning native layout: ${theme} ${width}px, all nine combinations`);
  }
 }finally{
   const owner=realpathSync(tmpdir()), target=realpathSync(tmp), child=relative(owner,target);
   assert(child&&!child.startsWith('..')&&!isAbsolute(child)&&dirname(child)==='.'&&basename(child).startsWith('lubi-planning-layout-'),'temporary cleanup must stay in the owned test directory');
   rmSync(target,{recursive:true,force:true});
 }
}
