// Projects are independent containers. Synthetic in-memory Vault; no personal data.
import assert from 'node:assert/strict';
import * as O from './mock-obsidian.js';
import Module from 'node:module';import {createRequire} from 'node:module';
import {blankTask,parseTaskImport} from './core.mjs';
const load=Module._load;Module._load=function(id,...args){return id==='obsidian'?O:load.call(this,id,...args)};
const Plugin=createRequire(import.meta.url)(process.env.LUBI_TEST_PLUGIN||'./plugin.cjs').default;
const app=new O.App(),plugin=new Plugin(app,{id:'lubi',version:'1.7.0'});await plugin.onload();await plugin.tasks.load();const path=plugin.settings.taskFile,D='2026-10-08';const wait=()=>new Promise(r=>setTimeout(r,240));
let p=await plugin.tasks.addProject('  考研数学  ');assert.equal(plugin.tasks.all.length,0);assert.equal(plugin.tasks.projectList.length,1);assert.equal((await plugin.tasks.addProject('考研数学')).id,p.id);await assert.rejects(plugin.tasks.addProject(' '));
await plugin.tasks.upsert(blankTask({id:'action-a',title:'导数学习',category:'学习',project:p.id,date:D,start:'08:00',estimate:30}));await plugin.tasks.upsert(blankTask({id:'action-b',title:'积分学习',category:'学习',project:p.id,date:D,start:'09:00',estimate:30}));await plugin.tasks.toggleDone('action-a',D);assert.equal(plugin.tasks.byId('action-b').status,'todo');assert(!('status'in plugin.tasks.projectList[0]));
const dataBeforeGrouping=JSON.stringify([...app.vault.files]);const view=await plugin.activateView('tasks',D);await wait();assert.equal(view.contentEl.querySelector('.lubi-plan-progress').getAttribute('aria-valuemax'),'2');assert([...view.contentEl.querySelectorAll('.lubi-plan-task-list .lubi-task-meta')].every(e=>!e.textContent.includes('考研数学')));const mathGroup=[...view.contentEl.querySelectorAll('.lubi-plan-task-list .lubi-task-group')].find(e=>e.querySelector('.lubi-task-group-title')?.textContent==='考研数学');assert(mathGroup);assert.equal(mathGroup.querySelectorAll('.lubi-task-group-title').length,1);assert.equal(mathGroup.querySelectorAll('.lubi-task').length,2);assert(!mathGroup.querySelector('.lubi-task-group-title input,.lubi-task-group-title button'));
assert.equal(JSON.stringify([...app.vault.files]),dataBeforeGrouping,'group rendering does not write data');view.contentEl.querySelector('.lubi-plan-task-details > summary').click();assert(!view.contentEl.querySelector('.lubi-plan-task-details').open);view.contentEl.querySelector('.lubi-plan-task-details > summary').click();assert(view.contentEl.querySelector('.lubi-plan-task-details').open);view.openNew();await wait();let form=O.openModals.at(-1);assert(![...form.contentEl.querySelectorAll('button')].some(e=>e.textContent.trim()==='父任务'));const projectToggle=[...form.contentEl.querySelectorAll('.lubi-extras-toggles button')].find(e=>e.textContent.trim()==='项目');assert(projectToggle);projectToggle.click();let name=form.contentEl.querySelector('[data-task-project=name]');name.value='考研英语';[...form.contentEl.querySelectorAll('button')].find(e=>e.textContent.trim()==='创建项目').click();await wait();const select=form.contentEl.querySelector('[data-task-project=select]');assert(select.value);assert.equal(plugin.tasks.projectList.find(p=>p.id===select.value).title,'考研英语');assert.equal(form.t.project,select.value);assert.equal(form.t.parent,null);form.t.title='背单词';await form.save();await wait();assert.equal(plugin.tasks.all.find(t=>t.title==='背单词').project,select.value);
// Legacy links are untouched until explicit conversion; all original task IDs and records survive.
await plugin.tasks.upsert(blankTask({id:'old-root',title:'旧数学',category:'学习',date:D,status:'done',customRootTask:{keep:true}}));await plugin.tasks.upsert(blankTask({id:'old-mid',title:'微积分',category:'学习',date:D,parent:'old-root'}));await plugin.tasks.upsert(blankTask({id:'old-leaf',title:'求导',category:'学习',date:D,parent:'old-mid',estimate:20}));await plugin.tasks.upsert(blankTask({id:'old-recorded-parent',title:'专项复习',category:'学习',parent:'old-root',date:D}));await plugin.tasks.upsert(blankTask({id:'old-recorded-child',title:'整理',category:'学习',parent:'old-recorded-parent',date:D}));
await plugin.tasks.upsert(blankTask({id:'old-span',title:'有明确任务跨度',category:'学习',parent:'old-root',startDate:D,endDate:D}));await plugin.tasks.upsert(blankTask({id:'old-span-child',title:'跨度内行动',category:'学习',parent:'old-span',date:D}));
await plugin.journal.add({date:D,start:'10:00',minutes:20,estimatedMinutes:15,title:'专项复习',category:'学习',task:'old-recorded-parent',extra:{自定义:'保留'}});
let raw=JSON.parse(app.vault.files.get(path));raw.customRoot={keep:true};app.vault.files.set(path,JSON.stringify(raw));await plugin.tasks.load(true);assert.equal(plugin.tasks.byId('old-leaf').parent,'old-mid');const journalBefore=app.vault.files.get(plugin.journal.path(D)),before=app.vault.files.get(path);
assert.equal(await plugin.tasks.convertParentsToProjects(new Set(['old-recorded-parent'])),1);assert.equal(app.vault.files.get(plugin.tasks.lastProjectBackup),before);assert.equal(app.vault.files.get(plugin.journal.path(D)),journalBefore);assert.equal(plugin.tasks.byId('old-leaf').parent,null);assert.equal(plugin.tasks.projectOf(plugin.tasks.byId('old-leaf')).title,'旧数学');assert(!plugin.tasks.all.some(t=>['old-root','old-mid'].includes(t.id)));assert(plugin.tasks.byId('old-root'));assert(plugin.tasks.all.some(t=>t.id==='old-span'),'independent explicit span retained');assert.equal(plugin.tasks.byId('old-root').status,'done');assert.deepEqual(plugin.tasks.byId('old-root').customRootTask,{keep:true});assert(plugin.tasks.all.some(t=>t.id==='old-recorded-parent'));assert.deepEqual(JSON.parse(app.vault.files.get(path)).customRoot,{keep:true});assert.equal(await plugin.tasks.convertParentsToProjects(new Set(['old-recorded-parent'])),0);
assert(!plugin.tasks.forDate(D).some(t=>t.id==='old-root'));assert(!plugin.tasks.inbox().some(t=>t.id==='old-mid'));
// Import projects are names, resolved once, without parent links or auto-completion.
const drafts=parseTaskImport(JSON.stringify({tasks:[{title:'词汇',category:'学习',project:'考研英语',date:D},{title:'阅读',category:'学习',project:'考研英语',date:D}]}),['学习']);await plugin.tasks.addBatch(drafts);assert.equal(plugin.tasks.projectOf(plugin.tasks.all.find(t=>t.title==='词汇')).title,'考研英语');assert.equal(plugin.tasks.all.find(t=>t.title==='阅读').parent,null);assert.equal(plugin.tasks.projectList.filter(p=>p.title==='考研英语').length,1);
const write=app.vault.adapter.write,processFile=app.vault.process.bind(app.vault);
for(const kind of ['backup','process']){const dataBefore=app.vault.files.get(path),memory=JSON.stringify(plugin.tasks.projectList);if(kind==='backup')app.vault.adapter.write=async()=>{throw Error('synthetic backup failure')};else app.vault.process=async()=>{throw Error('synthetic write failure')};await assert.rejects(plugin.tasks.addProject('失败项目'));assert.equal(app.vault.files.get(path),dataBefore);assert.equal(JSON.stringify(plugin.tasks.projectList),memory);app.vault.adapter.write=write;app.vault.process=processFile;}
const altered=JSON.parse(app.vault.files.get(path));altered.customRoot.external=true;app.vault.files.set(path,JSON.stringify(altered));await assert.rejects(plugin.tasks.addProject('外部冲突'));assert.equal(JSON.parse(app.vault.files.get(path)).customRoot.external,true);await plugin.tasks.load(true);
// Concurrent names deduplicate; queued task edits cannot disappear during project publication.
const both=await Promise.all([plugin.tasks.addProject('并发项目'),plugin.tasks.addProject('并发项目')]);assert.equal(both[0].id,both[1].id);
let release,started;const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r);app.vault.process=async(f,fn)=>{started();await gate;return processFile(f,fn)};const creating=plugin.tasks.addProject('保存中项目');await ready;const editing=plugin.tasks.upsert({...plugin.tasks.byId('action-b'),notes:'并发修改保留'});release();await Promise.all([creating,editing]);app.vault.process=processFile;assert.equal(plugin.tasks.byId('action-b').notes,'并发修改保留');assert.equal(JSON.parse(app.vault.files.get(path)).tasks.find(t=>t.id==='action-b').notes,'并发修改保留');
// Converting a later legacy batch cannot erase the first batch's original parent map.
await plugin.tasks.upsert(blankTask({id:'late-root',title:'后导入课题',category:'学习'}));await plugin.tasks.upsert(blankTask({id:'late-child',title:'后导入行动',category:'学习',parent:'late-root',date:D,estimate:10}));await plugin.tasks.convertParentsToProjects(new Set(['old-recorded-parent']));const links=JSON.parse(app.vault.files.get(path)).legacyParentLinks;assert.equal(links['old-leaf'],'old-mid');assert.equal(links['late-child'],'late-root');
// All Gantt periods group by actual projects, never actionable project summary bars.
await plugin.tasks.upsert(blankTask({id:'independent-gantt',title:'独立行动',category:'学习',date:D,start:'12:00',estimate:20}));
for(const period of ['day','week','month']) {
 view.tasksState.scheduleView='gantt';view.tasksState.period=period;view.show('tasks',D);await wait();
 const headings=[...view.contentEl.querySelectorAll('.lubi-gantt-project-heading')];assert(headings.some(e=>e.dataset.projectId===p.id));assert(headings.some(e=>e.textContent==='独立任务'));
 assert(headings.every(e=>!e.querySelector('input,button,.lubi-gantt-bar,.lubi-gantt-handle')&&!e.hasAttribute('data-task-id')));
 const math=headings.find(e=>e.dataset.projectId===p.id);assert.equal(math.nextElementSibling.dataset.taskId,'action-a');assert.equal(math.nextElementSibling.nextElementSibling.dataset.taskId,'action-b');
 assert.equal(headings.filter(e=>e.dataset.projectId===p.id).length,1);assert(headings.every(h=>h.querySelectorAll('.lubi-gantt-grid > div').length===(period==='day'?24:period==='week'?7:31)));assert.equal(math.nextElementSibling.querySelector('.lubi-gantt-name').style.getPropertyValue('--gantt-indent'),'8px');
}
for(const period of ['day','week','month']) {
 view.tasksState.scheduleView='list';view.tasksState.period=period;view.show('tasks',D);await wait();
 const row=view.contentEl.querySelector('.lubi-plan-range-list [data-task-id="action-a"]');assert(row);assert.equal(row.querySelector('.lubi-plan-list-parent').textContent,'考研数学');assert(!row.querySelector('.lubi-task-meta')?.textContent.includes('考研数学'),'list context appears only once');
}
view.show('today',D);await wait();const dayGroups=view.contentEl.querySelectorAll('.lubi-plan-task-list .lubi-task-group-title');assert([...dayGroups].some(e=>e.textContent==='独立任务'));assert.equal([...dayGroups].filter(e=>e.textContent==='考研数学').length,1);const plan=[...view.contentEl.querySelectorAll('.lubi-plan')].find(e=>e.textContent.includes('积分学习'));assert(plan);plan.focus();await wait();assert(document.querySelector('.lubi-tip')?.textContent.includes('项目：考研数学'));plan.blur();
console.log('PASS project views: day/week/month Gantt headings only, group membership, independent tasks, list context once and daily calendar details');
const settings=plugin.settingTabs[0];settings.display();assert(settings.containerEl.textContent.includes('旧父任务转为项目'));
await plugin.exportJson();const exported=JSON.parse([...app.vault.files].findLast(([f])=>f.startsWith('Lubi-导出-'))[1]);assert(exported.taskStore.projects.length);assert(exported.taskStore.projectContainers.includes('old-root'));assert(exported.records.some(r=>r.task==='old-recorded-parent'));
plugin.onunload();await view.onClose();console.log('PASS projects: independent containers, inline creation, membership, optional tasks, progress, explicit backed-up migration, archival IDs, actual records, import/export, failures, conflicts, duplicate creation and queued edits');
